name: wijt
description: My personal website.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.21.0+1

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/fonts/
  - assets/social_media/
  - assets/flag/tr.svg
  - assets/flag/us.svg
  
  fonts:
  - family: GoogleSansRegular
    fonts:
      - asset: assets/fonts/GoogleSansRegular.ttf


